config/routes.rb
Domased::Application.routes.draw do

  resources :facebook_places
  resources :users do
	member do
	  get 'settings'
	end
  end

  root 'public#home'
  
  resources :events do
  	collection do
		get 'calendar'
		get 'search'
	end
  end
  
  get '/about' => 'public#about'
  get '/login' => 'public#login'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/user.rb
class User < ActiveRecord::Base
  #validates_presence_of :username
  has_many :created_events, :class_name => "Event"  #user.created_events - zobrazi vsetky vytvorene eventy userom
  has_and_belongs_to_many :types
  
  def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
		  user.provider = auth.provider
		  user.uid = auth.uid
		  user.name = auth.info.name
		  user.oauth_token = auth.credentials.token
		  user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		  user.save!
	  end
  end

  def facebook
	@facebook ||= Koala::Facebook::API.new(oauth_token)
  end

  def admin?
	admin
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  def settings

  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:profile_text,:type_ids => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
		  <td><%= user.name %> </td>  
		<td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/settings.html.erb
<div class="container">
<h3>Profil</h3>
<%= form_for(@user) do |f| %>
		<div class="form-group">
          <%= f.label 'Profil' %>
          <%= f.text_area(:profile_text, :size => "3x3" ,class: 'form-control') %>
		</div>
		<div class="form-group">
			<%= f.label "Oblubene typy podujati:" %><br>
			<%= f.collection_check_boxes :type_ids, Type.all, :id, :name, :item_wrapper_class => 'inline' %>
	    </div>
	    <%= f.submit %>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<%= @user.name %>
<br><%= @user.profile_text %>

<br>Likes:

<ul>
<% @user.types.each do |like| %>
		<li><%= like.name %>
<% end %>
</ul>

<%= link_to 'Nastavenia', settings_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>