config/routes.rb
Domased::Application.routes.draw do

  resources :facebook_places
  resources :users do
	member do
	  get 'settings'
	end
  end

  root 'public#home'
  
  resources :events do
  	collection do
		get 'calendar'
		get 'search'
	end
  end
  
  get '/about' => 'public#about'
  get '/login' => 'public#login'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/facebook_place.rb
class FacebookPlace < ActiveRecord::Base
  validates :place_id, uniqueness: true
end

app/controllers/facebook_places_controller.rb
class FacebookPlacesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @facebook_places = FacebookPlace.order("created_at ASC")	#.paginate(page: params[:page])
  end

  # GET /facebook_places/1
  # GET /facebook_places/1.json
  def show
  end

  # GET /facebook_places/new
  def new
  end

  # GET /facebook_places/1/edit
  def edit
  end

  # POST /facebook_places
  # POST /facebook_places.json
  def create
    respond_to do |format|
      if @facebook_place.save
        format.html { redirect_to @facebook_place, notice: 'Facebook place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facebook_place }
      else
        format.html { render action: 'new' }
        format.json { render json: @facebook_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facebook_places/1
  # PATCH/PUT /facebook_places/1.json
  def update
    respond_to do |format|
      if @facebook_place.update(facebook_place_params)
        format.html { redirect_to @facebook_place, notice: 'Facebook place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facebook_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facebook_places/1
  # DELETE /facebook_places/1.json
  def destroy
    @facebook_place.destroy
    respond_to do |format|
      format.html { redirect_to facebook_places_url }
      format.json { head :no_content }
    end
  end

  private
        # Never trust parameters from the scary internet, only allow the white list through.
    def facebook_place_params
      params.require(:facebook_place).permit(:place_id, :name)
    end
end

app/helpers/facebook_places_helper.rb
module FacebookPlacesHelper
end

app/views/facebook_places/_form.html.erb
<%= form_for(@facebook_place) do |f| %>
  <% if @facebook_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facebook_place.errors.count, "error") %> prohibited this facebook_place from being saved:</h2>

      <ul>
      <% @facebook_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_id %><br>
    <%= f.text_field :place_id %>
  </div>
  <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facebook_places/edit.html.erb
<div class="container">
<h1>Editing facebook_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @facebook_place %> |
<%= link_to 'Back', facebook_places_path %>
</div>

app/views/facebook_places/index.html.erb
<div class="container">
<h1>Listing facebook_places(<%= FacebookPlace.all.count %>)</h1>
<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @facebook_places.each do |facebook_place| %>
      <tr>
        <td><%= facebook_place.place_id %></td>
        <td><%= facebook_place.name %></td>
		<td><%= link_to 'Facebook', "https://www.facebook.com/#{facebook_place.place_id}"  %></td>
		<td><%= link_to 'Show', facebook_place %></td>
		<% if can? :update, facebook_place %>
		<td><%= link_to 'Edit', edit_facebook_place_path(facebook_place) %></td>
		<% end %>
		<% if can? :destroy, facebook_place %>
		<td><%= link_to 'Destroy', facebook_place, method: :delete %></td>
		<% end %>
	</tr>
    <% end %>
	</tbody>
	<%#= will_paginate @facebook_places %>
</table>

<br>

<%= link_to 'New Facebook place', new_facebook_place_path %>
</div>

app/views/facebook_places/new.html.erb
<div class="container">
<h1>New facebook_place</h1>

<%= render 'form' %>

<%= link_to 'Back', facebook_places_path %>
</div>

app/views/facebook_places/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @facebook_place.place_id %>
</p>


<%= link_to 'Edit', edit_facebook_place_path(@facebook_place) %> |
<%= link_to 'Back', facebook_places_path %>
</div>