config/routes.rb
Domased::Application.routes.draw do

  resources :facebook_places
  resources :users do
	member do
	  get 'settings'
	end
  end

  root 'public#home'
  
  resources :events do
  	collection do
		get 'calendar'
		get 'search'
	end
  end
  
  get '/about' => 'public#about'
  get '/login' => 'public#login'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-footer col-md-6 col-xs-6">
        <h3>Kontakt</h3>
        <p class="contact-us-details">
          <div class= "col-md-6">
            <b>Email:</b> <a href="mailto:jakub.macina@gmail.com">jakub.macina@gmail.com</a>
          </div>
      </div>

      <div class="col-footer col-md-6 col-xs-6">
        <h3>Zostaň s nami</h3>
        <div class="footer-stay-connected no-list-style">
          <div class="row">
            <div class= "col-md-3"><a href="#" class="facebook"></a></div>
            <div class= "col-md-3"><a href="#" class="twitter"></a></div>
            <div class= "col-md-3"><a href="#" class="googleplus"></a></div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="footer-copyright">&copy; Jakub Mačina
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_ganalytics.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-52137132-1', 'domased.herokuapp.com');
ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<!-- Language and login-->
<div class="mainmenu-wrapper">
  <div class="container">
    <div class="menuextras">
      <div class="extras">
        <ul>
          <li>
            <div class="dropdown choose-country">
              <a class="#" data-toggle="dropdown" href="#"> <%= image_tag("sk.png", alt: "Slovak Republic") %> SK </a>
              <ul class="dropdown-menu" role="menu">
                <li role="menuitem"><a href="#"><%= image_tag("us.png", alt: "US") %> US</a></li>
              </ul>
            </div>
          </li>

            <% if current_user %>
                <li><strong><%= current_user.name %></strong></li>
                <li><%= link_to "Odhlásiť sa", signout_path, id: "sign_out" %></li>
            <% else %>
                <li><%= link_to('Prihlásenie', {:controller => 'public', :action => 'login'}) %></li>
            <% end %>




        </ul>
      </div>

      <!-- Navigation and logo -->
    </div>
    <nav id="mainmenu" class="mainmenu">
      <ul>
        <li class="logo-wrapper"><%= link_to image_tag("domased_logo.png"), {:controller => 'public', :action => 'home'} %></li>
        <li><%= link_to('Hlavná stránka', {:controller => 'public', :action => 'home'}) %></li>
        <li><%= link_to('Zoznam podujatí', events_path ) %></li>
        <li><%= link_to('Pridaj nové podujatie', new_event_path) %></li>
        <li><%= link_to('O nás', {:controller => 'public', :action => 'about'}) %></li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Jakub Macina">
  <link rel="shortcut icon" href="">

  <!-- Zobrazi page_title aj ked nie je instancia, app helper-->
  <title><%= full_title(@page_title) %></title>

  <!-- Bootstrap core CSS -->
  <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->
  <%= stylesheet_link_tag 'application', media: :all %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- Google API places library for autocomplete  -->
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>

  <!--&lt;!&ndash; Custom styles for this template &ndash;&gt;-->
  <!--<link href="jumbotron-narrow.css" rel="stylesheet">-->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<!--Header -->
<%= render 'layouts/header' %>

	<div class="container">
	<!--Flash message -->
	<% flash.each do |key,value| %>
      	<div class='alert alert-<%= key %>'>
			<button type='button' class='close' data-dismiss='alert'>×</button>
			<%= value %>
      	</div>
	<% end %>
	</div>

	<!-- Main body  -->
	<%= yield %>



<!--Footer -->
<%= render 'layouts/footer' %>

<!-- Google Analytics -->
<%= render 'layouts/ganalytics' %>

<!-- Debug  -->
<%= debug(params) if Rails.env.development? %>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
</body>
</html>